apiVersion: v1
kind: Namespace
metadata:
  name: retail-app
  labels:
    app: retail-management-system
    managed-by: helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: monitoring
    managed-by: helm
