apiVersion: v1
kind: Service
metadata:
  name: retail-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: retail-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
